kind: ConfigMap
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: policy
data:
  {{- range .Values.policy }}
  {{ .key }}: |
{{ .content | indent 3}}
  {{- end }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: opa-config
data:
  config.yaml: |
{{ .Values.config | indent 3 }}
