apiVersion: v1
kind: Service
metadata:
  name: opa-nginx
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8282
      protocol: TCP
      targetPort: 8282
  selector:
    app: opa-nginx
